### ISSUE TITLE
在ipone 6是plus运行

### ISSUE THREAD

**Issue by 812781385** [Middletwo-Kid/wechat-drag-image#1]
我在微信开发者工具上可以正常运行，但在真机上运行非常的卡顿

**Comment by Middletwo-Kid** [comment]
我等到现在才看到....
请问你是用我的demo直接在真机上运行的吗，我这个demo在真机上运行不卡顿；
如果不是我的demo的话，有木有设置movable相关标签的拖拽摩擦属性值

**Comment by 812781385** [comment]
真机调试的时候会卡（应该是log的原因），其它的形式不卡
